version: '3.3'
services:
  db:
    tty: true
    image: postgres
    env_file:
      - ./config/.database.env
    ports:
      - "5432"
  web:
    tty: true
    build: .
    command: ["./wait-for-it.sh","db:5432","--", "./build_script.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
