# Generated by Django 3.1.6 on 2021-03-28 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('steps', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDecoderApp.basicproducts')),
                ('id_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDecoderApp.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=1000)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDecoderApp.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Nutrients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('id_nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDecoderApp.nutrients')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDecoderApp.basicproducts')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipe_product',
            constraint=models.UniqueConstraint(fields=('id_recipe', 'id_product'), name='unique_key_pairs_recipe_product'),
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.UniqueConstraint(fields=('id_autor', 'id_recipe'), name='unique_key_pairs_autor_recipe'),
        ),
        migrations.AddConstraint(
            model_name='product_nutrients',
            constraint=models.UniqueConstraint(fields=('id_product', 'id_nutrient'), name='unique_key_pairs_product_nutrient'),
        ),
    ]
