# Generated by Django 3.1.6 on 2021-03-28 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishDecoderApp', '0002_auto_20210328_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_nutrients',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe_product',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
