# Generated by Django 3.1.6 on 2021-03-28 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishDecoderApp', '0003_auto_20210328_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_nutrients',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe_product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='steps',
            field=models.CharField(max_length=2000),
        ),
    ]
